// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/guilhermealvess/guicpay/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// AuthorizationService is an autogenerated mock type for the AuthorizationService type
type AuthorizationService struct {
	mock.Mock
}

// Authorize provides a mock function with given fields: ctx, account
func (_m *AuthorizationService) Authorize(ctx context.Context, account entity.Account) error {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthorizationService creates a new instance of AuthorizationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizationService {
	mock := &AuthorizationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
