version: "3.5"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=ozApGB6je7ZbK8wRGOh2zHG0qDfGcTi1yO78ieiQMN7eim2NfW
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    volumes:
      - ./infra/repository/sql:/docker-entrypoint-initdb.d

  zipkin:
    image: openzipkin/zipkin
    restart: always
    ports:
      - 9411:9411

  api:
    build: .
    environment:
      - APP_PORT=3000
      - TRANSACTION_TIMEOUT=15s
      - NOTIFICATION_SERVICE_URL=https://run.mocky.io/v3/5794d450-d2e2-4412-8131-73d0293ac1cc
      - AUTHORIZE_SERVICE_URL=https://run.mocky.io/v3/54dc2cf1-3add-45b5-b5a9-6bf7e7f1f4a6
      - DATABASE_URL=postgres://user:ozApGB6je7ZbK8wRGOh2zHG0qDfGcTi1yO78ieiQMN7eim2NfW@postgres:5432/db?sslmode=disable
      - JWT_SECRET=SECRET
      - TRACE_COLLECTOR_URL=http://zipkin:9411/api/v2/spans
      - USE_MOCK_SERVER=true
    depends_on:
      - postgres
      - zipkin
    deploy:
      replicas: 2
    restart: always
    command: ./guicpay
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  script:
    build:
      context: .
      dockerfile: Dockerfile.script
    depends_on:
      - nginx
    environment:
      - API_URL=http://api:3000
