FROM golang:1.22 AS builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o script cmd/script/main.go

FROM alpine:latest

RUN apk update && \
    apk add --no-cache tzdata && \
    apk add nano

WORKDIR /app

COPY --from=builder /app/script /app/.

RUN adduser -S guicpay -H && \
    chown -R guicpay: /app
USER guicpay

CMD [ "./script" ]
