version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - docker-network

  api:
    build: .
    environment:
      - APP_PORT=3000
      - TRANSACTION_TIMEOUT="5s"
      - NOTIFICATION_SERVICE_URL="https://run.mocky.io/v3/5794d450-d2e2-4412-8131-73d0293ac1cc"
      - AUTHORIZE_SERVICE_URL="https://run.mocky.io/v3/54dc2cf1-3add-45b5-b5a9-6bf7e7f1f4a6"
      - REDIS_ADDRESS="localhost:6379"
    ports:
      - 3000:3000
    depends_on:
      - redis
    networks:
      - docker-network
    command: ./guicpay

networks:
  docker-network:
    driver: bridge