version: "3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./infra/repository/sql:/docker-entrypoint-initdb.d

  redis:
    image: redis
    restart: always

  api:
    build: .
    environment:
      - APP_PORT=3000
      - TRANSACTION_TIMEOUT=5s
      - NOTIFICATION_SERVICE_URL=https://run.mocky.io/v3/5794d450-d2e2-4412-8131-73d0293ac1cc
      - AUTHORIZE_SERVICE_URL=https://run.mocky.io/v3/54dc2cf1-3add-45b5-b5a9-6bf7e7f1f4a6
      - REDIS_ADDRESS=redis:6379
      - DATABASE_URL=postgres://user:password@postgres:5432/db?sslmode=disable
    depends_on:
      - redis
      - postgres
    deploy:
      replicas: 2
    restart: always
    command: "./guicpay"

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
