version: "3"

services:
  redis:
    image: redis
    restart: always

  api:
    build: .
    environment:
      - APP_PORT=3000
      - TRANSACTION_TIMEOUT=5s
      - NOTIFICATION_SERVICE_URL=https://run.mocky.io/v3/5794d450-d2e2-4412-8131-73d0293ac1cc
      - AUTHORIZE_SERVICE_URL=https://run.mocky.io/v3/54dc2cf1-3add-45b5-b5a9-6bf7e7f1f4a6
      - REDIS_ADDRESS=redis:6379
    ports:
      - 3000:3000
    depends_on:
      - redis
    volumes:
      - ./guicpay.db:/app/guicpay.db:rw
    command: "./guicpay"

volumes:
  guicpay.db: