// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	pb "github.com/guilhermealvess/guicpay/pkg/pb"
)

// AccountsClient is an autogenerated mock type for the AccountsClient type
type AccountsClient struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, in, opts
func (_m *AccountsClient) Create(ctx context.Context, in *pb.CreateAccountRequest, opts ...grpc.CallOption) (*pb.CreateAccountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *pb.CreateAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CreateAccountRequest, ...grpc.CallOption) (*pb.CreateAccountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CreateAccountRequest, ...grpc.CallOption) *pb.CreateAccountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.CreateAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.CreateAccountRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Fetch provides a mock function with given fields: ctx, in, opts
func (_m *AccountsClient) Fetch(ctx context.Context, in *pb.FetchAccountRequest, opts ...grpc.CallOption) (*pb.FetchAccountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 *pb.FetchAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.FetchAccountRequest, ...grpc.CallOption) (*pb.FetchAccountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.FetchAccountRequest, ...grpc.CallOption) *pb.FetchAccountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.FetchAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.FetchAccountRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, in, opts
func (_m *AccountsClient) List(ctx context.Context, in *pb.ListRequest, opts ...grpc.CallOption) (*pb.ListResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *pb.ListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.ListRequest, ...grpc.CallOption) (*pb.ListResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.ListRequest, ...grpc.CallOption) *pb.ListResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.ListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.ListRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccountsClient creates a new instance of AccountsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountsClient {
	mock := &AccountsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
