// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	pb "github.com/guilhermealvess/guicpay/pkg/pb"
	mock "github.com/stretchr/testify/mock"
)

// AuthServer is an autogenerated mock type for the AuthServer type
type AuthServer struct {
	mock.Mock
}

// Auth provides a mock function with given fields: _a0, _a1
func (_m *AuthServer) Auth(_a0 context.Context, _a1 *pb.AuthRequest) (*pb.AuthResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Auth")
	}

	var r0 *pb.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.AuthRequest) (*pb.AuthResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.AuthRequest) *pb.AuthResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.AuthRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedAuthServer provides a mock function with given fields:
func (_m *AuthServer) mustEmbedUnimplementedAuthServer() {
	_m.Called()
}

// NewAuthServer creates a new instance of AuthServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServer {
	mock := &AuthServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
