// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	pb "github.com/guilhermealvess/guicpay/pkg/pb"
)

// TransactionsClient is an autogenerated mock type for the TransactionsClient type
type TransactionsClient struct {
	mock.Mock
}

// Deposit provides a mock function with given fields: ctx, in, opts
func (_m *TransactionsClient) Deposit(ctx context.Context, in *pb.DepositRequest, opts ...grpc.CallOption) (*pb.TransactionResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 *pb.TransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.DepositRequest, ...grpc.CallOption) (*pb.TransactionResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.DepositRequest, ...grpc.CallOption) *pb.TransactionResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.TransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.DepositRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Transfer provides a mock function with given fields: ctx, in, opts
func (_m *TransactionsClient) Transfer(ctx context.Context, in *pb.TransferRequest, opts ...grpc.CallOption) (*pb.TransactionResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Transfer")
	}

	var r0 *pb.TransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.TransferRequest, ...grpc.CallOption) (*pb.TransactionResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.TransferRequest, ...grpc.CallOption) *pb.TransactionResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.TransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.TransferRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionsClient creates a new instance of TransactionsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionsClient {
	mock := &TransactionsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
