// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	pb "github.com/guilhermealvess/guicpay/pkg/pb"
	mock "github.com/stretchr/testify/mock"
)

// TransactionsServer is an autogenerated mock type for the TransactionsServer type
type TransactionsServer struct {
	mock.Mock
}

// Deposit provides a mock function with given fields: _a0, _a1
func (_m *TransactionsServer) Deposit(_a0 context.Context, _a1 *pb.DepositRequest) (*pb.TransactionResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 *pb.TransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.DepositRequest) (*pb.TransactionResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.DepositRequest) *pb.TransactionResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.TransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.DepositRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Transfer provides a mock function with given fields: _a0, _a1
func (_m *TransactionsServer) Transfer(_a0 context.Context, _a1 *pb.TransferRequest) (*pb.TransactionResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Transfer")
	}

	var r0 *pb.TransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.TransferRequest) (*pb.TransactionResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.TransferRequest) *pb.TransactionResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.TransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.TransferRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedTransactionsServer provides a mock function with given fields:
func (_m *TransactionsServer) mustEmbedUnimplementedTransactionsServer() {
	_m.Called()
}

// NewTransactionsServer creates a new instance of TransactionsServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionsServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionsServer {
	mock := &TransactionsServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
