// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeAccountsServer is an autogenerated mock type for the UnsafeAccountsServer type
type UnsafeAccountsServer struct {
	mock.Mock
}

// mustEmbedUnimplementedAccountsServer provides a mock function with given fields:
func (_m *UnsafeAccountsServer) mustEmbedUnimplementedAccountsServer() {
	_m.Called()
}

// NewUnsafeAccountsServer creates a new instance of UnsafeAccountsServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeAccountsServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeAccountsServer {
	mock := &UnsafeAccountsServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
