// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeTransactionsServer is an autogenerated mock type for the UnsafeTransactionsServer type
type UnsafeTransactionsServer struct {
	mock.Mock
}

// mustEmbedUnimplementedTransactionsServer provides a mock function with given fields:
func (_m *UnsafeTransactionsServer) mustEmbedUnimplementedTransactionsServer() {
	_m.Called()
}

// NewUnsafeTransactionsServer creates a new instance of UnsafeTransactionsServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeTransactionsServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeTransactionsServer {
	mock := &UnsafeTransactionsServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
