// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"log"
	"os"

	"github.com/swaggo/swag"
)

var SwaggerInfo_swagger = &swag.Spec{
	Version:          "1.0",
	Host:             "petstore.swagger.io",
	BasePath:         "/v2",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "This is a sample server Petstore server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  read(),
}

func read() string {
	filePath := "./docs/swagger.yaml"
	content, err := os.ReadFile(filePath)
	if err != nil {
		log.Fatal("Error reading file:", err)
	}
	fileContent := string(content)
	return fileContent
}

func init() {
	swag.Register(SwaggerInfo_swagger.InstanceName(), SwaggerInfo_swagger)
}
