// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import ()

type Account struct {
	ID               interface{} `db:"id" json:"id"`
	AccountType      string      `db:"account_type" json:"account_type"`
	CustomerName     string      `db:"customer_name" json:"customer_name"`
	DocumentNumber   string      `db:"document_number" json:"document_number"`
	Email            string      `db:"email" json:"email"`
	PasswordEncoded  string      `db:"password_encoded" json:"password_encoded"`
	SaltHashPassword string      `db:"salt_hash_password" json:"salt_hash_password"`
	PhoneNumber      string      `db:"phone_number" json:"phone_number"`
	Status           string      `db:"status" json:"status"`
	CreatedAt        interface{} `db:"created_at" json:"created_at"`
	UpdatedAt        interface{} `db:"updated_at" json:"updated_at"`
}

type Transaction struct {
	ID              interface{} `db:"id" json:"id"`
	CorrelatedID    interface{} `db:"correlated_id" json:"correlated_id"`
	AccountID       interface{} `db:"account_id" json:"account_id"`
	TransactionType string      `db:"transaction_type" json:"transaction_type"`
	Timestamp       interface{} `db:"timestamp" json:"timestamp"`
	Amount          int64       `db:"amount" json:"amount"`
}
