// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
	"context"
)

type Querier interface {
	FindAccountByID(ctx context.Context, id interface{}) (FindAccountByIDRow, error)
	InsertNewAccount(ctx context.Context, arg InsertNewAccountParams) error
	InsertNewTransaction(ctx context.Context, arg InsertNewTransactionParams) error
}

var _ Querier = (*Queries)(nil)
